# ApiEndpoint Composition - Traditional Patch-and-Transform Pattern
# This Composition demonstrates Crossplane's built-in declarative composition
# It creates Lambda + API Gateway + IAM resources using Pipeline mode with patch-and-transform function
# Note: Crossplane v2 requires Pipeline mode even for "traditional" patches - Resources mode is deprecated

apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: apiendpoint-traditional
  labels:
    tutorial.crossplane.io/component: composition
    tutorial.crossplane.io/pattern: traditional-patches
    tutorial.crossplane.io/layer: poc
spec:
  compositeTypeRef:
    apiVersion: tutorial.crossplane.io/v1alpha1
    kind: XApiEndpoint

  mode: Pipeline

  pipeline:
  - step: patch-and-transform
    functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
      # IAM Role for Lambda execution
      - name: lambda-role
        base:
          apiVersion: iam.aws.upbound.io/v1beta1
          kind: Role
          spec:
            forProvider:
              assumeRolePolicy: |
                {
                  "Version": "2012-10-17",
                  "Statement": [
                    {
                      "Effect": "Allow",
                      "Principal": {
                        "Service": "lambda.amazonaws.com"
                      },
                      "Action": "sts:AssumeRole"
                    }
                  ]
                }
              tags:
                Purpose: xrd-tutorial-poc
                Component: lambda-role
            providerConfigRef:
              name: default
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.apiName
          toFieldPath: spec.forProvider.tags.ApiName
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.arn
          toFieldPath: status.iamRoleArn

      # Lambda Function
      - name: lambda-function
        base:
          apiVersion: lambda.aws.upbound.io/v1beta2
          kind: Function
          spec:
            forProvider:
              handler: lambda_function.handler
              region: us-east-1
              runtime: python3.11
              s3Bucket: "crossplane-tutorial-lambda-code-1766890187"
              s3Key: "lambda.zip"
              description: "ApiEndpoint Lambda - Updated for custom 404 response"
              tags:
                Purpose: xrd-tutorial-poc
                Component: lambda-function
            providerConfigRef:
              name: default
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.description
          toFieldPath: spec.forProvider.description
        - type: FromCompositeFieldPath
          fromFieldPath: spec.lambdaRuntime
          toFieldPath: spec.forProvider.runtime
        - type: FromCompositeFieldPath
          fromFieldPath: spec.apiName
          toFieldPath: spec.forProvider.tags.ApiName
        - type: FromCompositeFieldPath
          fromFieldPath: status.iamRoleArn
          toFieldPath: spec.forProvider.role
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.arn
          toFieldPath: status.lambdaArn
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.lastModified
          toFieldPath: status.deploymentTime

      # API Gateway HTTP API
      - name: api-gateway
        base:
          apiVersion: apigatewayv2.aws.upbound.io/v1beta1
          kind: API
          spec:
            forProvider:
              protocolType: HTTP
              region: us-east-1
              tags:
                Purpose: xrd-tutorial-poc
                Component: api-gateway
            providerConfigRef:
              name: default
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.apiName
          toFieldPath: spec.forProvider.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.description
          toFieldPath: spec.forProvider.description
        - type: FromCompositeFieldPath
          fromFieldPath: spec.apiName
          toFieldPath: spec.forProvider.tags.ApiName
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.apiEndpoint
          toFieldPath: status.endpointUrl
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.id
          toFieldPath: status.apiId

      # Default Integration - connects all unmatched requests to Lambda
      - name: default-integration
        base:
          apiVersion: apigatewayv2.aws.upbound.io/v1beta1
          kind: Integration
          spec:
            forProvider:
              integrationType: AWS_PROXY
              integrationMethod: POST
              region: us-east-1
            providerConfigRef:
              name: default
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: status.apiId
          toFieldPath: spec.forProvider.apiId
        - type: FromCompositeFieldPath
          fromFieldPath: status.lambdaArn
          toFieldPath: spec.forProvider.integrationUri

      # Lambda Permission for API Gateway
      - name: lambda-permission
        base:
          apiVersion: lambda.aws.upbound.io/v1beta1
          kind: Permission
          spec:
            forProvider:
              action: lambda:InvokeFunction
              principal: apigateway.amazonaws.com
              region: us-east-1
            providerConfigRef:
              name: default
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: status.lambdaArn
          toFieldPath: spec.forProvider.functionName
        - type: FromCompositeFieldPath
          fromFieldPath: status.apiId
          toFieldPath: spec.forProvider.sourceArn
          transforms:
          - type: string
            string:
              type: Format
              fmt: "arn:aws:execute-api:us-east-1:*:%s/*/*"