# Complete Prerequisite Infrastructure for XRD Tutorial
# This provides all foundational AWS infrastructure needed for the tutorial
# Learners will build ApiEndpoint and ApiRoute XRDs on top of this foundation

# Provider installations - these must be applied first
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-ec2
spec:
  package: xpkg.upbound.io/upbound/provider-aws-ec2:v2.3.0
  packagePullPolicy: IfNotPresent

---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-lambda
spec:
  package: xpkg.upbound.io/upbound/provider-aws-lambda:v2.3.0
  packagePullPolicy: IfNotPresent

---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-apigatewayv2
spec:
  package: xpkg.upbound.io/upbound/provider-aws-apigatewayv2:v2.3.0
  packagePullPolicy: IfNotPresent

---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-iam
spec:
  package: xpkg.upbound.io/upbound/provider-aws-iam:v2.3.0
  packagePullPolicy: IfNotPresent

---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-cloudwatch
spec:
  package: xpkg.upbound.io/upbound/provider-aws-cloudwatch:v2.3.0
  packagePullPolicy: IfNotPresent

# ProviderConfig - cluster-scoped (legacy for v1 compatibility)
---
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-secret
      key: credentials

# ProviderConfig - namespace-scoped for v2 managed resources
---
apiVersion: aws.m.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
  namespace: default
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: default
      name: aws-secret
      key: credentials

# VPC Infrastructure - foundational networking
---
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: VPC
metadata:
  namespace: default
  name: xrd-tutorial-vpc
  labels:
    tutorial.crossplane.io/component: infrastructure
    tutorial.crossplane.io/layer: prerequisite
spec:
  forProvider:
    cidrBlock: 10.0.0.0/16
    enableDnsHostnames: true
    enableDnsSupport: true
    region: us-east-1
    tags:
      Name: xrd-tutorial-vpc
      Purpose: crossplane-tutorial-foundation
      Layer: prerequisite
  providerConfigRef:
    name: default
    kind: ProviderConfig

---
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: Subnet
metadata:
  namespace: default
  name: xrd-tutorial-subnet-public-1a
  labels:
    tutorial.crossplane.io/component: infrastructure
    tutorial.crossplane.io/layer: prerequisite
    tutorial.crossplane.io/az: us-east-1a
spec:
  forProvider:
    availabilityZone: us-east-1a
    cidrBlock: 10.0.3.0/24
    mapPublicIpOnLaunch: true
    region: us-east-1
    vpcIdSelector:
      matchLabels:
        tutorial.crossplane.io/component: infrastructure
        tutorial.crossplane.io/layer: prerequisite
    tags:
      Name: xrd-tutorial-subnet-public-1a
      Purpose: crossplane-tutorial-foundation
      Layer: prerequisite
      AZ: us-east-1a
  providerConfigRef:
    name: default
    kind: ProviderConfig

---
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: Subnet
metadata:
  namespace: default
  name: xrd-tutorial-subnet-public-1b
  labels:
    tutorial.crossplane.io/component: infrastructure
    tutorial.crossplane.io/layer: prerequisite
    tutorial.crossplane.io/az: us-east-1b
spec:
  forProvider:
    availabilityZone: us-east-1b
    cidrBlock: 10.0.2.0/24
    mapPublicIpOnLaunch: true
    region: us-east-1
    vpcIdSelector:
      matchLabels:
        tutorial.crossplane.io/component: infrastructure
        tutorial.crossplane.io/layer: prerequisite
    tags:
      Name: xrd-tutorial-subnet-public-1b
      Purpose: crossplane-tutorial-foundation
      Layer: prerequisite
      AZ: us-east-1b
  providerConfigRef:
    name: default
    kind: ProviderConfig

---
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: InternetGateway
metadata:
  namespace: default
  name: xrd-tutorial-igw
  labels:
    tutorial.crossplane.io/component: infrastructure
    tutorial.crossplane.io/layer: prerequisite
spec:
  forProvider:
    region: us-east-1
    vpcIdSelector:
      matchLabels:
        tutorial.crossplane.io/component: infrastructure
        tutorial.crossplane.io/layer: prerequisite
    tags:
      Name: xrd-tutorial-igw
      Purpose: crossplane-tutorial-foundation
      Layer: prerequisite
  providerConfigRef:
    name: default
    kind: ProviderConfig

---
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: RouteTable
metadata:
  namespace: default
  name: xrd-tutorial-rt-public
  labels:
    tutorial.crossplane.io/component: infrastructure
    tutorial.crossplane.io/layer: prerequisite
spec:
  forProvider:
    region: us-east-1
    vpcIdSelector:
      matchLabels:
        tutorial.crossplane.io/component: infrastructure
        tutorial.crossplane.io/layer: prerequisite
    tags:
      Name: xrd-tutorial-rt-public
      Purpose: crossplane-tutorial-foundation
      Layer: prerequisite
  providerConfigRef:
    name: default
    kind: ProviderConfig

---
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: Route
metadata:
  namespace: default
  name: xrd-tutorial-route-public
  labels:
    tutorial.crossplane.io/component: infrastructure
    tutorial.crossplane.io/layer: prerequisite
spec:
  forProvider:
    destinationCidrBlock: 0.0.0.0/0
    gatewayIdSelector:
      matchLabels:
        tutorial.crossplane.io/component: infrastructure
        tutorial.crossplane.io/layer: prerequisite
    region: us-east-1
    routeTableIdSelector:
      matchLabels:
        tutorial.crossplane.io/component: infrastructure
        tutorial.crossplane.io/layer: prerequisite
  providerConfigRef:
    name: default
    kind: ProviderConfig

---
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  namespace: default
  name: xrd-tutorial-rta-public-1a
  labels:
    tutorial.crossplane.io/component: infrastructure
    tutorial.crossplane.io/layer: prerequisite
spec:
  forProvider:
    region: us-east-1
    routeTableIdSelector:
      matchLabels:
        tutorial.crossplane.io/component: infrastructure
        tutorial.crossplane.io/layer: prerequisite
    subnetIdSelector:
      matchLabels:
        tutorial.crossplane.io/component: infrastructure
        tutorial.crossplane.io/layer: prerequisite
        tutorial.crossplane.io/az: us-east-1a
  providerConfigRef:
    name: default
    kind: ProviderConfig

---
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  namespace: default
  name: xrd-tutorial-rta-public-1b
  labels:
    tutorial.crossplane.io/component: infrastructure
    tutorial.crossplane.io/layer: prerequisite
spec:
  forProvider:
    region: us-east-1
    routeTableIdSelector:
      matchLabels:
        tutorial.crossplane.io/component: infrastructure
        tutorial.crossplane.io/layer: prerequisite
    subnetIdSelector:
      matchLabels:
        tutorial.crossplane.io/component: infrastructure
        tutorial.crossplane.io/layer: prerequisite
        tutorial.crossplane.io/az: us-east-1b
  providerConfigRef:
    name: default
    kind: ProviderConfig

# Security Group for Lambda functions - allows outbound internet access
---
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: SecurityGroup
metadata:
  namespace: default
  name: xrd-tutorial-lambda-sg
  labels:
    tutorial.crossplane.io/component: infrastructure
    tutorial.crossplane.io/layer: prerequisite
    tutorial.crossplane.io/purpose: lambda
spec:
  forProvider:
    description: Security group for tutorial Lambda functions
    region: us-east-1
    vpcIdSelector:
      matchLabels:
        tutorial.crossplane.io/component: infrastructure
        tutorial.crossplane.io/layer: prerequisite
    tags:
      Name: xrd-tutorial-lambda-sg
      Purpose: crossplane-tutorial-foundation
      Layer: prerequisite
      Component: lambda-security
  providerConfigRef:
    name: default
    kind: ProviderConfig

---
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: SecurityGroupRule
metadata:
  namespace: default
  name: xrd-tutorial-lambda-egress-all
  labels:
    tutorial.crossplane.io/component: infrastructure
    tutorial.crossplane.io/layer: prerequisite
spec:
  forProvider:
    type: egress
    fromPort: 0
    toPort: 0
    protocol: "-1"
    cidrBlocks:
      - "0.0.0.0/0"
    region: us-east-1
    securityGroupIdSelector:
      matchLabels:
        tutorial.crossplane.io/component: infrastructure
        tutorial.crossplane.io/layer: prerequisite
        tutorial.crossplane.io/purpose: lambda
  providerConfigRef:
    name: default
    kind: ProviderConfig

# Basic IAM role for Lambda execution - will be extended by tutorial compositions
---
apiVersion: iam.aws.m.upbound.io/v1beta1
kind: Role
metadata:
  namespace: default
  name: xrd-tutorial-lambda-base-role
  labels:
    tutorial.crossplane.io/component: infrastructure
    tutorial.crossplane.io/layer: prerequisite
    tutorial.crossplane.io/purpose: lambda-base
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Service": "lambda.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
          }
        ]
      }
    tags:
      Name: xrd-tutorial-lambda-base-role
      Purpose: crossplane-tutorial-foundation
      Layer: prerequisite
  providerConfigRef:
    name: default
    kind: ProviderConfig

---
apiVersion: iam.aws.m.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  namespace: default
  name: xrd-tutorial-lambda-base-vpc-execution
  labels:
    tutorial.crossplane.io/component: infrastructure
    tutorial.crossplane.io/layer: prerequisite
spec:
  forProvider:
    policyArn: arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
    roleSelector:
      matchLabels:
        tutorial.crossplane.io/component: infrastructure
        tutorial.crossplane.io/layer: prerequisite
        tutorial.crossplane.io/purpose: lambda-base
  providerConfigRef:
    name: default
    kind: ProviderConfig

---
apiVersion: iam.aws.m.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  namespace: default
  name: xrd-tutorial-lambda-base-basic-execution
  labels:
    tutorial.crossplane.io/component: infrastructure
    tutorial.crossplane.io/layer: prerequisite
spec:
  forProvider:
    policyArn: arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    roleSelector:
      matchLabels:
        tutorial.crossplane.io/component: infrastructure
        tutorial.crossplane.io/layer: prerequisite
        tutorial.crossplane.io/purpose: lambda-base
  providerConfigRef:
    name: default
    kind: ProviderConfig