# Basic VPC Infrastructure for XRD Tutorial Testing
# This provides the foundational AWS networking for the proof-of-concept

apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  name: xrd-tutorial-vpc
  labels:
    tutorial.crossplane.io/component: infrastructure
spec:
  forProvider:
    cidrBlock: 10.0.0.0/16
    enableDnsHostnames: true
    enableDnsSupport: true
    region: us-east-1
    tags:
      Name: xrd-tutorial-vpc
      Purpose: crossplane-tutorial-testing
  providerConfigRef:
    name: default

---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: xrd-tutorial-subnet-public
  labels:
    tutorial.crossplane.io/component: infrastructure
spec:
  forProvider:
    availabilityZone: us-east-1a
    cidrBlock: 10.0.1.0/24
    mapPublicIpOnLaunch: true
    region: us-east-1
    vpcIdSelector:
      matchLabels:
        tutorial.crossplane.io/component: infrastructure
    tags:
      Name: xrd-tutorial-subnet-public
      Purpose: crossplane-tutorial-testing
  providerConfigRef:
    name: default

---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: InternetGateway
metadata:
  name: xrd-tutorial-igw
  labels:
    tutorial.crossplane.io/component: infrastructure
spec:
  forProvider:
    region: us-east-1
    vpcIdSelector:
      matchLabels:
        tutorial.crossplane.io/component: infrastructure
    tags:
      Name: xrd-tutorial-igw
      Purpose: crossplane-tutorial-testing
  providerConfigRef:
    name: default

---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTable
metadata:
  name: xrd-tutorial-rt-public
  labels:
    tutorial.crossplane.io/component: infrastructure
spec:
  forProvider:
    region: us-east-1
    vpcIdSelector:
      matchLabels:
        tutorial.crossplane.io/component: infrastructure
    tags:
      Name: xrd-tutorial-rt-public
      Purpose: crossplane-tutorial-testing
  providerConfigRef:
    name: default

---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Route
metadata:
  name: xrd-tutorial-route-public
  labels:
    tutorial.crossplane.io/component: infrastructure
spec:
  forProvider:
    destinationCidrBlock: 0.0.0.0/0
    gatewayIdSelector:
      matchLabels:
        tutorial.crossplane.io/component: infrastructure
    region: us-east-1
    routeTableIdSelector:
      matchLabels:
        tutorial.crossplane.io/component: infrastructure
  providerConfigRef:
    name: default

---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  name: xrd-tutorial-rta-public
  labels:
    tutorial.crossplane.io/component: infrastructure
spec:
  forProvider:
    region: us-east-1
    routeTableIdSelector:
      matchLabels:
        tutorial.crossplane.io/component: infrastructure
    subnetIdSelector:
      matchLabels:
        tutorial.crossplane.io/component: infrastructure
  providerConfigRef:
    name: default