#!/bin/bash

# Example Usage Script for XRD Tutorial Environment Setup
# This shows how to set the required environment variables and run the setup

echo "📖 XRD Tutorial Environment Setup - Example Usage"
echo "================================================="
echo ""

echo "This script demonstrates how to set up the environment variables"
echo "and run the complete environment setup."
echo ""

echo "🔧 AWS Credentials Setup Options:"
echo ""
echo "Option 1: Use existing config file (recommended)"
echo "source ~/.config/env-mk8-aws"
echo "./scripts/setup-complete-environment.sh"
echo ""
echo "Option 2: Set environment variables manually"
echo "export AWS_ACCESS_KEY_ID=\"AKIA...\""
echo "export AWS_SECRET_ACCESS_KEY=\"...\""
echo "export AWS_DEFAULT_REGION=\"us-east-1\""
echo "./scripts/setup-complete-environment.sh"
echo ""

echo "📋 Complete Setup Process:"
echo ""
echo "# Method 1: Using config file (if available)"
echo "source ~/.config/env-mk8-aws"
echo "./scripts/setup-complete-environment.sh"
echo ""
echo "# Method 2: Manual environment variables"
echo "export AWS_ACCESS_KEY_ID=\"AKIAIOSFODNN7EXAMPLE\""
echo "export AWS_SECRET_ACCESS_KEY=\"wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY\""
echo "export AWS_DEFAULT_REGION=\"us-east-1\""
echo "./scripts/setup-complete-environment.sh"
echo ""

echo "🚨 Security Notes:"
echo ""
echo "- Never commit AWS credentials to git repositories"
echo "- Use environment variables or AWS credential files"
echo "- Consider using AWS IAM roles for production environments"
echo "- The setup script validates credential format before proceeding"
echo ""

echo "🎯 What the setup script does:"
echo ""
echo "1. ✅ Validates AWS credentials from environment variables"
echo "2. 🔧 Checks Kubernetes cluster access"
echo "3. 📦 Installs Crossplane v2.1+ (if not already installed)"
echo "4. 🔌 Installs Upbound AWS Provider Family"
echo "5. 🔐 Configures AWS authentication for Crossplane"
echo "6. 🖥️  Configures AWS CLI"
echo "7. 🏗️  Runs the POC environment restoration"
echo "8. 🔍 Performs final verification"
echo ""

echo "📊 After successful setup, you can verify with:"
echo ""
echo "./scripts/show-current-status.sh"
echo "./scripts/verify-prerequisites.sh"
echo "kubectl get xapiendpoint test-apiendpoint -o yaml"
echo ""

echo "💡 Troubleshooting:"
echo ""
echo "If the script fails:"
echo "- Check that your AWS credentials are valid"
echo "- Ensure kubectl can access your Kubernetes cluster"
echo "- Verify you have sufficient AWS permissions"
echo "- Check that helm is installed for Crossplane installation"
echo ""

echo "🎉 Ready to run? Set your environment variables and execute:"
echo "./scripts/setup-complete-environment.sh"